export default {
  "code": "200",
  "data": {
    "title": "居家生活",
    "hasMore": true,
    "itemList": [{
      "id": 1110003,
      "name": "裸睡亲肤 经典A类针织四件套",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/9a33f08a3b0f5c06fdf4c586d51b2f7c.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/b04d88a9ceb8f1a7fd11d0d9e9de6311.jpg",
      "retailPrice": 259,
      "activityPrice": "208",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "够柔够弹针织棉，亲肤可裸睡",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "5色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [],
      "goodRate": "99.6%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/64e13d749dcf26c2cf89ffb5e71e345b.png",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "23万+评价",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": "爆款",
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": "预售狂欢",
          "price": null,
          "content": "预定立省¥51 仅剩2天"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": null,
            "price": "208",
            "suffix": null
          },
          "counterPrice": "259",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 1516008,
      "name": "不与螨虫一起睡，真丝枕套",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/6b172c71a23491d31db63b97a39f1f53.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/38cd07a95f60ed615de12ccdcc34bb4d.jpg",
      "retailPrice": 99,
      "activityPrice": "89",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "入门级奢品，真丝细润亲肤",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "3色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [],
      "goodRate": "99.8%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/53bcc64c3ea4b69e8e377302f1e32cec.png",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "9万+评价",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": "爆款",
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": null,
          "price": {
            "prefix": "每日抄底",
            "price": "85",
            "suffix": null
          },
          "content": "3.31 20点开抢"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": null,
            "price": "89",
            "suffix": null
          },
          "counterPrice": "99",
          "basicPrice": null
        },
        "type": 1
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698653574d07eb.png",
        "width": 36,
        "height": 36,
        "type": 1
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 3413004,
      "name": "【经典升级】新贵轻奢，60支锦眠贡缎四件套",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/fd808031a37d0eeabcefb81d3244f18d.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/3820097eb6bff1dd972d8a12a2b3bd43.jpg",
      "retailPrice": 469,
      "activityPrice": "348",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "高密纯棉贡缎，入门奢享",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "7色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [],
      "goodRate": "99.7%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/f5834aa971b9500e6add9c87f1896f01.jpg",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "5万+评价",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": "爆款",
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": "预售狂欢",
          "price": null,
          "content": "预定立省¥121 仅剩2天"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": null,
            "price": "348",
            "suffix": null
          },
          "counterPrice": "469",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 3428015,
      "name": "【新疆棉】日式全棉格纹四件套 新款",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/b1f7d3096d12d0e4f9e0bbc7232e9295.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/0b9f4c027c417d25c56c0b8af439ee6d.png",
      "retailPrice": 299,
      "activityPrice": "239",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "日式水洗工艺，慵懒自然",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "8色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [{
        "type": 15,
        "name": "可用红包",
        "itemTag": null,
        "itemTagType": null,
        "freshmanExclusive": false
      }],
      "goodRate": "99.7%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/f987f15aa4a31ef7d882a5a828965bba.jpg",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "5万+评价",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": "爆款",
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": null,
          "price": null,
          "content": "每满200减20券"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": "到手",
            "price": "189",
            "suffix": null
          },
          "counterPrice": "299",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698653574d07eb.png",
        "width": 36,
        "height": 36,
        "type": 1
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 3458041,
      "name": "A类便携裸睡，60支柔光贡缎睡袋",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/81e4cb829d3e165768fb19914c6f0273.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/0bf3d6679c6a2d0d6b975494ccf7d0c6.png",
      "retailPrice": 149,
      "activityPrice": "97",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "严苛A类标准，一体式设计",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "3色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [],
      "goodRate": "99.7%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/f1076753e6088bc82bda7062d76c2b66.jpg",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "1万+评价",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": null,
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": "清仓价",
          "price": null,
          "content": "仅剩1天"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": null,
            "price": "97",
            "suffix": null
          },
          "counterPrice": "149",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 3459027,
      "name": "丝滑亲肤棉感，A类60支天丝棉四件套",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/8759994ef547a286ae91ea1d435a1a2b.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/e84e7346b9efd12251bc4eb94e0ca369.png",
      "retailPrice": 699,
      "activityPrice": "318",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "1. LF天丝与长绒棉黄金配比，真丝工艺织造，7A级超柔，肌底无感裸睡\n2. 母婴A类，敏感肌不怕过敏\n3.无纺布包装，送礼、换洗、收耐方便\n4.活性印染，环保健康",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "4色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [],
      "goodRate": "99.7%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/be1e031ff53cf4c6bdd7b365181899f2.png",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "5211评价",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": "爆款",
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": "预售狂欢",
          "price": null,
          "content": "预定立省¥381 仅剩2天"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": null,
            "price": "318",
            "suffix": null
          },
          "counterPrice": "699",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 3989227,
      "name": "佳偶天成 锦上添花 婚庆乔迁床品套装",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/70e7d248ed15150527f2a2df4daa05d1.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/0f5e8742c52f8a37dcf3686c7d9bf0fd.png",
      "retailPrice": 999,
      "activityPrice": "839",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "精致刺绣，贡缎面料，寓意富贵美满",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "5色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [{
        "type": 15,
        "name": "可用红包",
        "itemTag": null,
        "itemTagType": null,
        "freshmanExclusive": false
      }],
      "goodRate": "99.6%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/091b7a4bd404d083eb572f680d4ad9b4.jpg",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": null,
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": null,
          "price": null,
          "content": "满99减30元"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": "到手",
            "price": "809",
            "suffix": null
          },
          "counterPrice": "999",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 3990946,
      "name": "【老罗推荐】A类天竺棉全棉针织拼色四件套",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/6010c18ccebc679a1654d5f74c8cfe19.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/89c9bc4021888d2cace0e70314a30c79.png",
      "retailPrice": 319,
      "activityPrice": "209",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "内衣般柔弹，纯棉吸汗透气，舒适裸睡",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "6色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [{
        "type": 15,
        "name": "可用红包",
        "itemTag": null,
        "itemTagType": null,
        "freshmanExclusive": false
      }],
      "goodRate": "99.7%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/f292148de794236aa68088e6ad59e5c4.png",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "6万+评价",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": null,
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": null,
          "price": null,
          "content": "每满200减20券"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": "到手",
            "price": "159",
            "suffix": null
          },
          "counterPrice": "319",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 3993054,
      "name": "奢密丝滑，埃及长绒棉高支高密床品件套",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/e179ee1e8e35fd0d5b4b3ab31ec30931.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/6332921d119c5bb64a5af2bde1d859bc.png",
      "retailPrice": 389,
      "activityPrice": "349",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "140支800根纱线高密贡缎织造，纵享品质睡眠",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "12色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [],
      "goodRate": "99.4%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/e48a41fc1b6979ba0061d139788ada95.png",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": null,
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": "囤货特价",
          "price": null,
          "content": "仅剩2天"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": null,
            "price": "349",
            "suffix": null
          },
          "counterPrice": "389",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 3993713,
      "name": "高阶奢华·真丝四件套",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/8a32219dfe2f7eecacba52a96e608c23.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/e27ff799edcff31ee6007948d85020ea.jpg",
      "retailPrice": 3699,
      "activityPrice": "2558",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "100%桑蚕丝，丝滑润肤",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "5色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [],
      "goodRate": "99.2%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/1c3e68f1e01a88531913e60ab9cce967.jpg",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": "爆款",
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": "预售狂欢",
          "price": null,
          "content": "预定立省¥1141 仅剩2天"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": null,
            "price": "2558",
            "suffix": null
          },
          "counterPrice": "3699",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 3997731,
      "name": "【新疆棉】绵柔服软，A类全棉水洗棉四件套",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/986656764a93fbdbb7d383ab715454df.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/d1515bcc5b257b2316a2f1c6996ba77a.jpg",
      "retailPrice": 339,
      "activityPrice": "198",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "会呼吸的水洗棉，日式慵懒做旧风",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "4色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [],
      "goodRate": "99.5%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/5f7e04ba1d52d9dbdb26eb4ca1f48d84.png",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": "爆款",
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": "预售狂欢",
          "price": null,
          "content": "预定立省¥141 仅剩2天"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": null,
            "price": "198",
            "suffix": null
          },
          "counterPrice": "339",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 3997945,
      "name": "【新疆棉】A类亲肤，60支柔光贡缎四件套",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/0a736015b346ff8699c06b334979a02c.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/91221398d5ffc158d3d100857a6687aa.png",
      "retailPrice": 299,
      "activityPrice": "239",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "60支织就柔软质感，婴幼儿级A类标准",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "4色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [{
        "type": 15,
        "name": "可用红包",
        "itemTag": null,
        "itemTagType": null,
        "freshmanExclusive": false
      }],
      "goodRate": "99.4%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/245a3d288c603ebb2e3d4124b0b61f28.jpg",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "1万+评价",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": "爆款",
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": null,
          "price": null,
          "content": "每满200减20券"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": "到手",
            "price": "189",
            "suffix": null
          },
          "counterPrice": "299",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 3999131,
      "name": "冰能科技®A类温和凉感 果冻床笠三件套",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/712776a6b1bb92d15bf3697e02963fea.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/54b1632d4690d6c851e44f89eb7d07d1.png",
      "retailPrice": 79,
      "activityPrice": "55",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "黑科技纤维，亲肤透气，真丝般顺滑舒爽",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": null,
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [],
      "goodRate": "99.4%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/41df4cecf03dacd4202b27babb2986e8.png",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "1万+评价",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": null,
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": null,
          "price": {
            "prefix": "每日抄底",
            "price": "35",
            "suffix": null
          },
          "content": "3.31 20点开抢"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": null,
            "price": "55",
            "suffix": null
          },
          "counterPrice": "79",
          "basicPrice": null
        },
        "type": 1
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 3999313,
      "name": "跳舞的线，60S长绒棉印花四件套",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/0e746b050b86afb237a5559e2e614b75.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/eb916e44cb656e29870376ac79a23dff.png",
      "retailPrice": 469,
      "activityPrice": "282",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "100%新疆长绒棉，原创印花设计",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "4色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [],
      "goodRate": "99.4%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/4361aeecb580642069b7985e0a8ae5bd.png",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": null,
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": null,
          "price": null,
          "content": "每满200减20券"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": "到手",
            "price": "262",
            "suffix": null
          },
          "counterPrice": "469",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 4003194,
      "name": "奢享酒店美学，100支全棉贡缎刺绣四件套",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/46cfe4f3ee9b28568c22a4a3efb1d71c.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/b1e2418a17b592250cd9764e13a61875.jpg",
      "retailPrice": 819,
      "activityPrice": "799",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "100%新疆长绒棉，极致奢享",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "4色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [],
      "goodRate": "99.3%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/52dde56efdd71303cd99c46671ddb283.jpg",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": null,
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": "限时优惠",
          "price": null,
          "content": "仅剩2天"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": null,
            "price": "799",
            "suffix": null
          },
          "counterPrice": "819",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 4004214,
      "name": "柔软轻奢睡眠，80支高支棉儿童套件",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/10e02921559d8918dca044a5fb436c11.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/82114f253f70a73712a3ea89e85bfb6d.png",
      "retailPrice": 399.00,
      "activityPrice": null,
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "80支贡缎，顺滑柔软透气好，防螨抗菌洁净好睡",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": null,
      "unShelf": false,
      "limitedFlag": false,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [],
      "goodRate": "98.7%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/18fe64060c3b457445b5f8f69a556cfd.png",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": null,
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": null,
        "priceInfo": {
          "finalPrice": null,
          "counterPrice": null,
          "basicPrice": "399"
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": false
    }, {
      "id": 4004293,
      "name": "沁入湖水般清凉，冰能科技60支兰精天丝床笠",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/56dcdd9cae8ad577244ce85452dc2f27.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/f105719d736e0771686f7dac3fd8ea2c.png",
      "retailPrice": 149,
      "activityPrice": "129",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "奥地利兰精天丝，真丝般软糯丝滑",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": null,
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [{
        "type": 15,
        "name": "可用红包",
        "itemTag": null,
        "itemTagType": null,
        "freshmanExclusive": false
      }],
      "goodRate": "99.7%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/e2687c417a46d5c8fdc44a730eac4b5f.png",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "5688评价",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": null,
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": null,
          "price": null,
          "content": "满99减30元"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": "到手",
            "price": "99",
            "suffix": null
          },
          "counterPrice": "149",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 4004732,
      "name": "【他牌代销1.0】曼妙柔滑真丝三件套/单品",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/3ac537cb7a0755793d4a13e0a8ae0795.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/2bac1b51ffe2fa4af07636dc8a340efa.jpg",
      "retailPrice": 229,
      "activityPrice": null,
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "水润丝滑，曼妙柔滑",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": null,
      "unShelf": false,
      "limitedFlag": false,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [{
        "type": 15,
        "name": "可用红包",
        "itemTag": null,
        "itemTagType": null,
        "freshmanExclusive": false
      }],
      "goodRate": "99.7%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/c8e8b4508c771b9cafedb1092f69d6bf.jpg",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": null,
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": null,
          "price": null,
          "content": "满99减30元"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": "到手",
            "price": "199",
            "suffix": null
          },
          "counterPrice": "229",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": false
    }, {
      "id": 4008520,
      "name": "法国进口亚麻，肌理素色水洗床上件套",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/03e6508bf85ab0edd0716b442f6994f9.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/f8fb02073ab5977f4e6631dbc45ad3d9.png",
      "retailPrice": 179,
      "activityPrice": "147",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "法国诺曼底亚麻，透气吸汗，散热性好",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "4色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [],
      "goodRate": "99.8%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/4b0dc7c6bdfb5b12880aaae70dee5927.png",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": null,
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": "限时优惠",
          "price": null,
          "content": "仅剩2天"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": null,
            "price": "147",
            "suffix": null
          },
          "counterPrice": "179",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }, {
      "id": 4010317,
      "name": "A类裸睡绵感，120支长绒棉提花四件套",
      "categoryId": 109323008,
      "primaryPicUrl": "https://yanxuan-item.nosdn.127.net/ba0c478e898538f98c48e426b884836e.png",
      "listPicUrl": "https://yanxuan-item.nosdn.127.net/f0da92516ca6e53d2864d0d949e2e337.png",
      "retailPrice": 769,
      "activityPrice": "679",
      "soldOut": false,
      "few": false,
      "last": false,
      "simpleDesc": "高支纱贡缎，轻奢提花肌理",
      "simpleDescClose": false,
      "extraPrice": "",
      "newOnShelf": false,
      "forSale": false,
      "specification": "2色可选",
      "unShelf": false,
      "limitedFlag": true,
      "limitedTag": "",
      "productPlace": "",
      "itemTagList": [{
        "type": 15,
        "name": "可用红包",
        "itemTag": null,
        "itemTagType": null,
        "freshmanExclusive": false
      }],
      "goodRate": "99.3%好评率",
      "heat": null,
      "repoCount": null,
      "scenePicUrl": "https://yanxuan-item.nosdn.127.net/e23a6aaf9b3cf84d6ba3d085bc8996d3.png",
      "freshman": false,
      "appExclusiveFlag": false,
      "accessTime": 0,
      "promotionFlag": 0,
      "specTag": null,
      "comments": null,
      "commentCount": "",
      "promBanner": null,
      "promLogo": null,
      "couponTag": null,
      "couponPrice": null,
      "depositSwapped": false,
      "returnPrice": null,
      "hotListDesc": null,
      "hotListJumpTarget": null,
      "salePointDesc": null,
      "extra": null,
      "rankInfo": null,
      "finalPriceInfoVO": {
        "banner": {
          "logo": null,
          "title": null,
          "price": null,
          "content": "每满200减20券"
        },
        "priceInfo": {
          "finalPrice": {
            "prefix": "到手",
            "price": "589",
            "suffix": null
          },
          "counterPrice": "769",
          "basicPrice": null
        },
        "type": 0
      },
      "topLogo": {
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/1678945986e1f775.png",
        "width": 105,
        "height": 54,
        "type": 3
      },
      "preLogo": [{
        "logoUrl": "https://yanxuan.nosdn.127.net/static-union/16698631101bcf18.png",
        "width": 30,
        "height": 30,
        "type": 0
      }],
      "promDesc": null,
      "targetJump": null,
      "orderBackValid": false,
      "limitedSingleProm": true
    }],
    "categoryL2List": [{
      "id": 0,
      "name": "全部"
    }, {
      "id": 1008009,
      "name": "四件套"
    }, {
      "id": 109323008,
      "name": "四季款"
    }, {
      "id": 109323009,
      "name": "秋冬款"
    }, {
      "id": 109323013,
      "name": "床笠枕套"
    }, {
      "id": 109329011,
      "name": "被子"
    }, {
      "id": 109329030,
      "name": "乳胶枕"
    }, {
      "id": 109323016,
      "name": "枕头"
    }, {
      "id": 109323017,
      "name": "盖毯"
    }, {
      "id": 109323019,
      "name": "儿童床品"
    }, {
      "id": 109329014,
      "name": "毯子"
    }, {
      "id": 109323000,
      "name": "办公椅/工学椅"
    }, {
      "id": 109323001,
      "name": "书桌/儿童学习书桌"
    }, {
      "id": 109323002,
      "name": "升降台/支架"
    }, {
      "id": 109323024,
      "name": "床垫"
    }, {
      "id": 109323025,
      "name": "床褥"
    }, {
      "id": 109329029,
      "name": "乳胶床垫"
    }, {
      "id": 109323020,
      "name": "毛巾/浴巾"
    }, {
      "id": 109323021,
      "name": "抱枕/坐垫"
    }, {
      "id": 109323022,
      "name": "地垫/地毯"
    }, {
      "id": 109323023,
      "name": "其他布艺"
    }, {
      "id": 109331001,
      "name": "取暖电器"
    }, {
      "id": 109331002,
      "name": "电子马桶盖"
    }, {
      "id": 109334043,
      "name": "炸烤箱"
    }, {
      "id": 109334044,
      "name": "咖啡机"
    }, {
      "id": 109334045,
      "name": "电热水壶"
    }, {
      "id": 109334046,
      "name": "养生壶"
    }, {
      "id": 109334047,
      "name": "电饭煲/电磁炉"
    }, {
      "id": 109331000,
      "name": "空气净化"
    }, {
      "id": 109334048,
      "name": "更多厨房小电"
    }, {
      "id": 1005007,
      "name": "品质锅具"
    }, {
      "id": 1007000,
      "name": "保温杯/壶"
    }, {
      "id": 1005008,
      "name": "颜值餐具"
    }, {
      "id": 1005009,
      "name": "厨房纸品"
    }, {
      "id": 109288006,
      "name": "厨房清洁剂/皂"
    }, {
      "id": 109323014,
      "name": "清洁工具"
    }, {
      "id": 1013005,
      "name": "刀剪砧板"
    }, {
      "id": 1008012,
      "name": "餐厨配件"
    }, {
      "id": 109324000,
      "name": "茶具"
    }, {
      "id": 109324001,
      "name": "酒具"
    }, {
      "id": 1092010,
      "name": "收纳柜/箱"
    }, {
      "id": 109243004,
      "name": "收纳篮/袋"
    }, {
      "id": 109331003,
      "name": "厨房收纳"
    }, {
      "id": 109243006,
      "name": "床/床头柜"
    }, {
      "id": 109319000,
      "name": "沙发/沙发床"
    }, {
      "id": 109243007,
      "name": "休闲椅/凳"
    }, {
      "id": 109252033,
      "name": "茶几/电视柜"
    }, {
      "id": 109302000,
      "name": "餐桌椅"
    }, {
      "id": 109243009,
      "name": "餐边柜/储物柜"
    }, {
      "id": 1008016,
      "name": "鞋架/衣帽架"
    }, {
      "id": 109323003,
      "name": "卫浴净水"
    }, {
      "id": 109323004,
      "name": "开关/灯具"
    }, {
      "id": 109308000,
      "name": "养生保健"
    }, {
      "id": 109293000,
      "name": "医疗工具"
    }, {
      "id": 1008017,
      "name": "衣架/净化除味"
    }, {
      "id": 1011004,
      "name": "办公文具"
    }, {
      "id": 109305000,
      "name": "花艺/装饰品"
    }, {
      "id": 109323005,
      "name": "镜子/挂钟/香薰"
    }, {
      "id": 109323006,
      "name": "趣味玩具"
    }, {
      "id": 109323007,
      "name": "唱片CD"
    }]
  }
}